import {Listing,Profile,Conversation,Message} from '@/types/models';

const now=new Date();
export const demoCommunityCircles=['Ramat Yishai','Kiryat Tivon','Nahalal','Kfar Yehoshua'];
export const demoProfile:Profile={id:'demo-user',full_name:'Maya Cohen',city:process.env.EXPO_PUBLIC_DEMO_CITY||'Ramat Yishai',neighborhood:'Local circle',rating_avg:4.9,rating_count:18,completed_count:24,items_given_away:18,items_lent:6,requests_fulfilled:9,estimated_waste_saved_kg:72,community_circles:['Ramat Yishai','Kiryat Tivon'],created_at:'2025-03-01T00:00:00Z'};
const owner=(id:string,full_name:string,completed_count=8):Profile=>({...demoProfile,id,full_name,completed_count,rating_avg:4.7+completed_count/100});
export const demoListings:Listing[]=[
  {id:'demo-lemons',owner_id:'u1',type:'OFFER',category:'produce',title:'Free lemons from my tree',description:'I have a lemon tree with more lemons than I can use. Anyone nearby is welcome to come and take some.',quantity:'A small bag',status:'available',city:'Ramat Yishai',neighborhood:'Near Ramat Yishai',community_circle:'Ramat Yishai',lat:32.7041,lng:35.1729,created_at:new Date(now.getTime()-25*60000).toISOString(),owner:owner('u1','Noa Levi',22)},
  {id:'demo-books',owner_id:'u2',type:'OFFER',category:'books',title:'Free children’s books',description:'Giving away children’s books in good condition.',status:'available',city:'Kiryat Tivon',neighborhood:'Kiryat Tivon',community_circle:'Kiryat Tivon',lat:32.7209,lng:35.1279,created_at:new Date(now.getTime()-2*3600e3).toISOString(),owner:owner('u2','Amir Bar',14)},
  {id:'demo-drill',owner_id:'u3',type:'LEND',category:'tools',title:'Drill available to borrow',description:'I have a drill that neighbors can borrow for the weekend.',status:'available',city:'Kfar Yehoshua',neighborhood:'Kfar Yehoshua',community_circle:'Kfar Yehoshua',lat:32.6818,lng:35.1556,created_at:new Date(now.getTime()-4*3600e3).toISOString(),owner:owner('u3','Lior Dan',9)},
  {id:'demo-veg',owner_id:'u4',type:'OFFER',category:'produce',title:'Fresh vegetables from the garden',description:'Extra vegetables from my garden, free for anyone nearby.',status:'available',city:'Nahalal',neighborhood:'Nahalal',community_circle:'Nahalal',lat:32.6915,lng:35.1964,created_at:new Date(now.getTime()-7*3600e3).toISOString(),owner:owner('u4','Yael Green',31)},
  {id:'demo-cycling',owner_id:'u5',type:'ACTIVITY',category:'community',title:'Looking for a cycling partner',description:'Looking for someone nearby to join a weekend bicycle ride.',status:'available',city:'Kiryat Tivon / Ramat Yishai',neighborhood:'Between Kiryat Tivon and Ramat Yishai',community_circle:'Ramat Yishai',lat:32.7122,lng:35.1511,created_at:new Date(now.getTime()-50*60000).toISOString(),owner:owner('u5','Tamar Ride',6)},
  {id:'demo-request',owner_id:'u6',type:'REQUEST',category:'help',title:'Looking for moving boxes',description:'Does anyone nearby have clean moving boxes to spare this week?',status:'available',city:'Ramat Yishai',neighborhood:'Ramat Yishai',community_circle:'Ramat Yishai',lat:32.7073,lng:35.1672,created_at:new Date(now.getTime()-90*60000).toISOString(),owner:owner('u6','Eden Mor',5)}
];
export const demoConversations:Conversation[]=[{id:'c1',listing_id:'demo-lemons',participant_a:'demo-user',participant_b:'u1',last_message:'Sure, after 17:00 works.',last_message_at:new Date().toISOString(),created_at:new Date().toISOString(),listing:demoListings[0],other_user:demoListings[0].owner}];
export const demoMessages:Message[]=[{id:'m1',conversation_id:'c1',sender_id:'demo-user',body:'Are the lemons still available?',created_at:new Date(Date.now()-1800e3).toISOString()},{id:'m2',conversation_id:'c1',sender_id:'u1',body:'Sure, after 17:00 works.',created_at:new Date().toISOString()}];
